apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servicename-to-containerid-mapping-role
  namespace: mynamespace
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch"]     