apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicename-to-containerid-mapping-rolebinding
  namespace: mynamespace
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: servicename-to-containerid-mapping-role
  apiGroup: rbac.authorization.k8s.io